---
name: Integration tests on Azure
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - v*
  pull_request_target:
    types: [labeled]

jobs:
  integration-tests-azure:
    name: Integration tests on Azure
    if: contains(github.event.pull_request.labels.*.name, 'safe to test') || github.ref_name == 'master' || startsWith(github.ref_name, 'v')
    strategy:
      max-parallel: 1
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        msodbc_version: ["17", "18"]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbt-msft/dbt-sqlserver:CI-${{ matrix.python_version }}-msodbc${{ matrix.msodbc_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r dev_requirements.txt

      # - name: Resume server
      #   env:
      #     DBT_SYNAPSE_SERVER: ${{ secrets.DBT_SYNAPSE_SERVER }}
      #     DBT_SYNAPSE_DB: ${{ secrets.DBT_SYNAPSE_DB }}
      #     AZURE_CLIENT_ID: ${{ secrets.DBT_AZURE_SP_NAME }}
      #     AZURE_CLIENT_SECRET: ${{ secrets.DBT_AZURE_SP_SECRET }}
      #     AZURE_TENANT_ID: ${{ secrets.DBT_AZURE_TENANT }}
      #     DBT_AZURE_RESOURCE_GROUP_NAME: ${{ secrets.DBT_AZURE_RESOURCE_GROUP_NAME }}
      #     DBT_AZURE_SUBSCRIPTION_ID: ${{ secrets.DBT_AZURE_SUBSCRIPTION_ID }}
      #   run: python devops/synapse.py resume

      # - name: Configure test users
      #   run: sqlcmd -b -I -i devops/create_sql_users.sql
      #   env:
      #     DBT_TEST_USER_1: DBT_TEST_USER_1
      #     DBT_TEST_USER_2: DBT_TEST_USER_2
      #     DBT_TEST_USER_3: DBT_TEST_USER_3
      #     SQLCMDUSER: ${{ secrets.DBT_SYNAPSE_UID }}
      #     SQLCMDPASSWORD: ${{ secrets.DBT_SYNAPSE_PWD }}
      #     SQLCMDSERVER: ${{ secrets.DBT_SYNAPSE_SERVER }}.sql.azuresynapse.net
      #     SQLCMDDBNAME: ${{ secrets.DBT_SYNAPSE_DB }}

      - name: Run functional tests
        env:
          DBT_SYNAPSE_SERVER: ${{ secrets.DBT_SYNAPSE_SERVER }}
          DBT_SYNAPSE_DB: ${{ secrets.DBT_SYNAPSE_DB }}
          AZURE_CLIENT_ID: ${{ secrets.DBT_AZURE_SP_NAME }}
          AZURE_CLIENT_SECRET: ${{ secrets.DBT_AZURE_SP_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.DBT_AZURE_TENANT }}
          DBT_TEST_USER_1: DBT_TEST_USER_1
          DBT_TEST_USER_2: DBT_TEST_USER_2
          DBT_TEST_USER_3: DBT_TEST_USER_3
          DBT_TEST_AAD_PRINCIPAL_1: ${{ secrets.DBT_TEST_AAD_PRINCIPAL_1 }}
          DBT_TEST_AAD_PRINCIPAL_2: ${{ secrets.DBT_TEST_AAD_PRINCIPAL_2 }}
          SYNAPSE_TEST_DRIVER: 'ODBC Driver ${{ matrix.msodbc_version }} for SQL Server'
        run: pytest -ra -v tests/functional --profile "ci_azure_auto"
